#- name: "Proyecto"
#  link: "/proyecto"
- name: "Mortalidad"
  link: "/mortalidad"
- name: "Egresos"
  link: "/egresos"
- name: "Causas"
  link: "/causas"
- name: "Nosortos"
  link: "/nosotros"
#- name: "About"
#  link: "/about"
#- name: "Graficas"
#  link: "/graficas"
