#- name: "Proyecto"
#  link: "/proyecto"
- name: "Mortalidad"
  link: "/mortalidad"
- name: "Egresos"
  link: "/egresos"
- name: "¿Qué nos dejó la pandemia hasta ahora?"
  link: "/que-nos-dejo"
- name: "Nosortos"
  link: "/nosotros"
