#- name: "Proyecto"
#  link: "/proyecto"
- name: "Intro"
  link: "/"
- name: "Mortalidad"
  link: "/mortalidad"
- name: "Glosario"
  link: "/glosario"
- name: "Nosotros"
  link: "/nosotros"
#- name: "About"
#  link: "/about"
#- name: "Graficas"
#  link: "/graficas"
